name: bazi_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  iconify_flutter: ^0.0.7
  intl: ^0.20.2
  table_calendar: ^3.2.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/BaziHarmonyLogo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
          weight: 700
        - asset: assets/fonts/CinzelDecorative-Black.ttf
          weight: 900
    - family: ChironSungHK
      fonts:
        - asset: assets/fonts/ChironSungHK-VariableFont_wght.ttf
          weight: 900
        - asset: assets/fonts/ChironSungHK-Italic-VariableFont_wght.ttf
          style: italic

smooth_page_indicator: ^1.1.0